### PR TITLE
describe how to use jupyter on an HPC as well

### PR DESCRIPTION
**Pull request by aryarm**
this PR adds some additional helpful text to the wiki

@ziqixu091 , once you get a chance to try this out, can you reply here letting us know whether it works? also, feel free to suggest any edits that would make the tutorial easier for people to understand!

### CODE REVIEW

**Comment by aryarm** [comment]
@ziqixu091, I added clarifications in a872aae . Do they cover everything we discussed?

**Comment by ziqixu091** [comment]
I think it looks great!

**Review by ziqixu091 — COMMENTED** [review]
The instructions are all tested on HPC. Ready for merging.

**Comment by aryarm** [comment]
merging without approval

**Pull request merged**
