### PR TITLE
automate builds using readthedocs

### LINKED ISSUE #1: add contributing guidelines

### LINKED ISSUE #4: Fail checks if sphinx warnings
Can we fail pr checks if there are any sphinx warnings? Those are usually indicative of larger problems

### PR DESCRIPTION
**Pull request by aryarm**
resolves #4 and creates a new contributing doc

### CODE REVIEW

**Comment by aryarm** [comment]
@mikecuoco , what do you think?

If the build fails, you can view the build failure messages by clicking "Details" on the right

Otherwise, you can click on the same thing to view the built webpage before it gets merged into the main branch

**Comment by aryarm** [comment]
TODO: images aren't loading and I still want to include info about building the docs locally from the readme

The images aren't loaded because I used html [apparently](https://jupyterbook.org/en/stable/advanced/html.html#raw-html-in-markdown)

Also we should probably say something about adding pages to our TOC

**Comment by aryarm** [comment]
@mikecuoco, what do you think of the new contributing doc? you can preview it on this branch here:

https://bioinfo-ucsd-wiki--12.org.readthedocs.build/docs/contributing.html

I tried to write it to require very little prior experience with git

**Comment by mikecuoco** [comment]
> @mikecuoco, what do you think of the new contributing doc? you can preview it here:
> 
> https://bioinfo-ucsd-wiki--12.org.readthedocs.build/docs/contributing.html
> 
> I tried to write it such that very little prior experience with git would be needed by the contributor

Looks great. Have you tested it?

**Comment by aryarm** [comment]
yeah! I kinda followed my own instructions as I was making the contributing doc

**Comment by aryarm** [comment]
gonna merge without explicit review approval

**Pull request merged**
